
    [{
      id: 0,
      product: 'Blue Skies',
      serialnumber: '37843',
      price: 54.95,
      manufacturer: 'Kiwi Photography',
      category: 'country scenery',
      img: './assets/blueskies.jpg',
    }, {
        id: 1,
        product: 'Boot and Spur',
        serialnumber: '37462',
        price: 24.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/bootandspur.jpg',
    }, {
        id: 2,
        product: 'Break Time',
        serialnumber: '32542',
        price: 69.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/breaktime.jpg',
    }, {
        id: 3,
        product: 'Bridle',
        serialnumber: '36422',
        price: 23.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/bridle.jpg',
    }, {
        id: 4,
        product: 'Buckskin Barrel Saddle',
        serialnumber: '37798',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: './assets/buckskin.jpg',
   
    }, {
        id: 5,
        product: 'Family Horse',
        serialnumber: '37654',
        price: 44.95,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: './assets/cowboyhathorse.jpg',
    }, {
        id: 6,
        product: 'Little Cowboy',
        serialnumber: '49642',
        price: 59.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/littlecowboy.jpg',
    }, {
        id: 7,
        product: 'Nap Time',
        serialnumber: '39023',
        price: 59.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/naptime.jpg',
    }, {
        id: 8,
        product: 'Peaceful Ride',
        serialnumber: '37444',
        price: 49.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/peacefulride.jpg',
    }, {
        id: 9,
        product: 'Pretty Buckskin',
        serialnumber: '35442',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: './assets/prettybuckskin.jpg',
    }, {
        id: 10,
        product: 'Romance on Horseback',
        serialnumber: '37841',
        price: 49.95,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: './assets/romancehorseback.jpg',
    }, {
        id: 11,
        product: 'Getting After It',
        serialnumber: '51842',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/roping.jpg',
    }, {
        id: 12,
        product: 'Saddle Up',
        serialnumber: '67841',
        price: 45.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/saddleup.jpg',
    }, {
        id: 13,
        product: 'Sheep Herd',
        serialnumber: '77841',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: './assets/sheep.jpg',
    }, {
        id: 14,
        product: 'Herding Sheep',
        serialnumber: '35942',
        price: 44.95,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: './assets/sheepherding.jpg',
    }, {
        id: 15,
        product: 'Sheep in Chute',
        serialnumber: '37332',
        price: 29.95,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: './assets/sheepinchute.jpg',
   
    }, {
        id: 16,
        product: 'Sorrel',
        serialnumber: '38841',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: './assets/sorrel.jpg',
    }, {
        id: 17,
        product: 'Country Sunset',
        serialnumber: '87841',
        price: 49.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/sunset.jpg',
    }, {
        id: 18,
        product: 'Evening Sunset',
        serialnumber: '37842',
        price: 59.95,
        manufacturer: 'Kiwi Photography',
        category: 'country scenery',
        img: './assets/swcountry.jpg',
    }, {
        id: 19,
        product: 'True Grit',
        serialnumber: '34472',
        price: 44.95,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: './assets/truegrit.jpg',
    }, {
        id: 20,
        product: 'Waiting Patiently',
        serialnumber: '64847',
        price: 39.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/waitingpatiently.jpg',
    }, {
        id: 21,
        product: 'Working Cattle',
        serialnumber: '74842',
        price: 34.95,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: './assets/workingcattle.jpg',
    
    },
]
