const data =
    [{
      id: 0,
      name: 'Blue Skies',
      serialnumber: '37843',
      price: 54.95,
      inventoryQuantity: 15,
      cartQuantity: 1,
      manufacturer: 'Kiwi Photography',
      category: 'country scenery',
      img: 'http://goldencrossranch.com/capstone1images/blueskies.jpg',
    }, {
        id: 1,
        name: 'Boot and Spur',
        serialnumber: '37462',
        price: 24.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/bootandspur.jpg',
    }, {   
        id: 2,
        name: 'Break Time',
        serialnumber: '32542',
        price: 69.95,
        inventoryQuantity: 0,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/breaktime.jpg',
    }, {
        
        id: 3,
        name: 'True Grit',
        serialnumber: '34472',
        price: 44.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/truegrit.jpg',
    }, {
        id: 4,
        name: 'Buckskin Barrel Saddle',
        serialnumber: '37798',
        price: 39.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: 'http://goldencrossranch.com/capstone1images/buckskin.jpg',
   
    }, {
        id: 5,
        name: 'Family Horse',
        serialnumber: '37654',
        price: 44.95,
        inventoryQuantity: 0,
        cartQuantity: 1,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/cowboyhathorse.jpg',
    }, {
        id: 6,
        name: 'Little Cowboy',
        serialnumber: '49642',
        price: 59.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/littlecowboy.jpg',
    }, {
        id: 7,
        name: 'Nap Time',
        serialnumber: '39023',
        price: 59.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/naptime.jpg'
    }, {
        id: 8,
        name: 'Peaceful Ride',
        serialnumber: '37444',
        price: 49.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/peacefulride.jpg',
    }, {
        id: 9,
        name: 'Pretty Buckskin',
        serialnumber: '35442',
        price: 39.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: 'http://goldencrossranch.com/capstone1images/prettybuckskin.jpg',
    }, {
        id: 10,
        name: 'Romance on Horseback',
        serialnumber: '37841',
        price: 49.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Golden Cross Ranch LLC',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/romancehorseback.jpg',
    }, {
        id: 11,
        name: 'Getting After It',
        serialnumber: '51842',
        price: 39.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/roping.jpg',
    }, {
        id: 12,
        name: 'Saddle Up',
        serialnumber: '67841',
        price: 45.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/saddleup.jpg',
    }, {
        id: 13,
        name: 'Sheep Herd',
        serialnumber: '77841',
        price: 39.95,
        inventoryQuantity: 15,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: 'http://goldencrossranch.com/capstone1images/sheep.jpg',
    }, {
        id: 14,
        name: 'Herding Sheep',
        serialnumber: '35942',
        price: 44.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: 'http://goldencrossranch.com/capstone1images/sheepherding.jpg',
    }, {
        id: 15,
        name: 'Sheep in Chute',
        serialnumber: '37332',
        price: 29.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'sheep',
        img: 'http://goldencrossranch.com/capstone1images/sheepinchute.jpg',
   
    }, {
        id: 16,
        name: 'Sorrel',
        serialnumber: '38841',
        price: 39.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'horses',
        img: 'http://goldencrossranch.com/capstone1images/sorrel.jpg',
    }, {
        id: 17,
        name: 'Country Sunset',
        serialnumber: '87841',
        price: 49.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/sunset.jpg',
    }, {
        id: 18,
        name: 'Evening Sunset',
        serialnumber: '37842',
        price: 59.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country scenery',
        img: 'http://goldencrossranch.com/capstone1images/swcountry.jpg',
    }, {
        id: 19,
        name: 'Waiting Patiently',
        serialnumber: '64847',
        price: 39.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/waitingpatiently.jpg',
    }, {
        id: 20,
        name: 'Bridle',
        serialnumber: '36422',
        price: 23.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/bridle.jpg',
    }, {
        id: 21,
        name: 'Working Cattle',
        serialnumber: '74842',
        price: 34.95,
        inventoryQuantity: 15,
        cartQuantity: 1,
        manufacturer: 'Kiwi Photography',
        category: 'country life',
        img: 'http://goldencrossranch.com/capstone1images/workingcattle.jpg',
    
    },
]


export default data; 

        